"""empty message

Revision ID: 4283b7809499
Revises: 945a0f15546d
Create Date: 2024-10-12 12:01:05.719274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4283b7809499'
down_revision = '945a0f15546d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=255), nullable=True))
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
