"""modificando o bd para refletir os campos do form relatar ocorrencia

Revision ID: 58073d6c81f0
Revises: 5ca5bf52dd19
Create Date: 2024-10-13 22:01:17.146534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58073d6c81f0'
down_revision = '5ca5bf52dd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sobrenome', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.drop_column('sobrenome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
