"""modificando o bd para refletir os campos do form relatar ocorrencia

Revision ID: 5ca5bf52dd19
Revises: 6c5b587e3147
Create Date: 2024-10-13 20:29:57.668705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ca5bf52dd19'
down_revision = '6c5b587e3147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_interior', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('outro_problema', sa.String(length=100), nullable=True))
        batch_op.drop_column('sobrenome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('sobrenome', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('outro_problema')
        batch_op.drop_column('nome_interior')

    # ### end Alembic commands ###
