"""Add sobrenome, cpf, email, and endereco to Usuario

Revision ID: 794f15d7abc4
Revises: 35cf916bf6a3
Create Date: 2024-10-10 11:33:32.910377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794f15d7abc4'
down_revision = '35cf916bf6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocorrencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('localizacao', sa.String(length=255), nullable=False),
    sa.Column('tipo_problema', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sobrenome', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('sobrenome')

    op.drop_table('ocorrencia')
    # ### end Alembic commands ###
