"""empty message

Revision ID: 945a0f15546d
Revises: c4ded6524a45
Create Date: 2024-10-12 12:00:42.477098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '945a0f15546d'
down_revision = 'c4ded6524a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=255), nullable=True))
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
